@host = http://localhost:3101


### ----------GET PRODUCTS------------


### ALL PRODUCTS FOR NON-ADMIN

GET {{host}}/api/products

### RETURN ALL PRODUCT ATTRIBUTES (ALSO STOCK)

GET {{host}}/api/products/
x-token: admin2024

### FILTER BY NAME AND CATEGORY FOR NON-ADMIN

GET {{host}}/api/products?name=a&category=b

### FILTER BY PRICE RANGE FOR NON-ADMIN

GET {{host}}/api/products?min=30&max=50


### ----------GET PRODUCTS BY ID------------

### GET PRODUCT BY ID (VALID ID AND NON-ADMIN)
GET {{host}}/api/products/2

### GET PRODUCT BY ID (VALID ID) (ADMIN)
GET {{host}}/api/products/2
x-token: admin2024
### GET PRODUCT BY ID (INVALID ID)
GET {{host}}/api/products/1000

### ----------POST PRODUCTS------------

### ADD A PRODUCT OK (ADMIN)

POST {{host}}/api/products
Content-Type: application/json
x-token: admin2024

{
  "imageUrl": "image url",
  "name": "product1",
  "description": "description1",
  "unit": "unit1",
  "category": "category1",
  "pricePerUnit": 12.34,
  "stock": 10
}

### ADD A PRODUCT (MISSING PROPERTIES)

POST {{host}}/api/products
Content-Type: application/json
x-token: admin2024

{
  "imageUrl": "image url",
  "name": "product1"
}
### ADD A PRODUCT (ADMIN) (REPEATED NAME)

POST {{host}}/api/products
Content-Type: application/json
x-token: admin2024

{
  "imageUrl": "image",
  "name": "product1",
  "description": "desc1",
  "unit": "u",
  "category": "cat",
  "pricePerUnit": 12.34,
  "stock": 10
}

### ADD A PRODUCT (MISSING X-TOKEN)

POST {{host}}/api/products
Content-Type: application/json

{
  "imageUrl": "image",
  "name": "product1",
  "description": "desc1",
  "unit": "u",
  "category": "cat",
  "pricePerUnit": 12.34,
  "stock": 10
}


### ADD A PRODUCT (X-TOKEN NOT ADMIN)

POST {{host}}/api/products
Content-Type: application/json
x-token: admin2020

{
  "imageUrl": "image",
  "name": "product1",
  "description": "desc1",
  "unit": "u",
  "category": "cat",
  "pricePerUnit": 12.34,
  "stock": 10
}

### ----------PUT PRODUCTS------------

### UPDATE PRODUCT OK (ADMIN)

PUT {{host}}/api/products/Nzpt
Content-Type: application/json
x-token: admin2024

{
  "imageUrl": "NEW BETTER IMAGE!!!",
  "name": "flashy name",
  "description": "cool desc",
  "unit": "tons",
  "category": "dark matter",
  "pricePerUnit": 100000.00,
  "stock": 1
}
### UPDATE PRODUCT (MISSING PROPERTIES)
PUT {{host}}/api/products/Nzpt
Content-Type: application/json
x-token: admin2024

{
  "description": "cool desc",
  "unit": "tons",
  "category": "dark matter",
  "pricePerUnit": 100000.00,
  "stock": 1
}
### UPDATE PRODUCT (ADMIN) (REPEATED NAME)
PUT {{host}}/api/products/Nzpt
Content-Type: application/json
x-token: admin2024

{
  "imageUrl": "NEW BETTER IMAGE!!!",
  "name": "flashy name",
  "description": "cool desc",
  "unit": "tons",
  "category": "dark matter",
  "pricePerUnit": 100000.00,
  "stock": 1
}

### UPDATE PRODUCT (MISSING X-TOKEN)
PUT {{host}}/api/products/Nzpt
Content-Type: application/json

{
  "imageUrl": "NEW BETTER IMAGE!!!",
  "name": "flashy name",
  "description": "cool desc",
  "unit": "tons",
  "category": "dark matter",
  "pricePerUnit": 100000.00,
  "stock": 1
}
### UPDATE PRODUCT (X-TOKEN NOT ADMIN)
PUT {{host}}/api/products/Nzpt
Content-Type: application/json
x-token: admin2020

{
  "imageUrl": "NEW BETTER IMAGE!!!",
  "name": "flashy name",
  "description": "cool desc",
  "unit": "tons",
  "category": "dark matter",
  "pricePerUnit": 100000.00,
  "stock": 1
}
### ----------DELETE PRODUCTS------------

### DELETE PRODUCT OK (ADMIN)

DELETE {{host}}/api/products/Nzpt
x-token: admin2024

### DELETE PRODUCT (MISSING X-TOKEN)

DELETE {{host}}/api/products/Nzpt

### DELETE PRODUCT (X-TOKEN NOT ADMIN)

DELETE {{host}}/api/products/Nzpt
x-token: admin2020
